spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/post_dev
    username: lldj
    password: lldj123414
  jpa:
    hibernate:
      ddl-auto: create

decorator:
  datasource:
    p6spy:
      enable-logging: true